liste_utilisateurs:
    path:     /utilisateurs
    defaults: { _controller: UserBundle:Default:listeDesUtilisateurs }

liste_utilisateurs_role:
    path:     /utilisateurs/{role}
    defaults: { _controller: UserBundle:Default:listeDesUtilisateurParRole }
    methods:  [GET, POST]