user_admin_utilisateurs:
    resource: "@UserBundle/Resources/config/user.yml"
    prefix:   /admin/utilisateurs

liste_utilisateurs:
    path:     /moncompte
    defaults: { _controller: UserBundle:Default:utilisateur }
