fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


app2:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /



_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
