fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

nao_contact:
    resource: "@NAOContactBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


app_observation:
    resource: "@AppBundle/Resources/config/observation.yml"
    prefix:   /observation
